In [5]:
import numpy as np
import pandas as pd
import ast
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import pickle

In [ ]:
#!pip install nltk

^C

Requirement already satisfied: nltk in c:\users\farhaan\anaconda3\envs\tf_gpu_ana_env\lib\site-packages (3.9.1)
Requirement already satisfied: click in c:\users\farhaan\anaconda3\envs\tf_gpu_ana_env\lib\site-packages (from nltk) (8.1.8)
Requirement already satisfied: joblib in c:\users\farhaan\anaconda3\envs\tf_gpu_ana_env\lib\site-packages (from nltk) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in c:\users\farhaan\anaconda3\envs\tf_gpu_ana_env\lib\site-packages (from nltk) (2024.11.6)
Requirement already satisfied: tqdm in c:\users\farhaan\anaconda3\envs\tf_gpu_ana_env\lib\site-packages (from nltk) (4.67.3)
Requirement already satisfied: colorama in c:\users\farhaan\anaconda3\envs\tf_gpu_ana_env\lib\site-packages (from click->nltk) (0.4.6)

In [6]:
# Load datasets
movie = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv("tmdb_5000_credits.csv")

C:\Users\Farhaan\AppData\Local\Temp\ipykernel_3084\542805098.py:3: DtypeWarning: Columns (0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,376,377,378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418,419,420,421,422,423,424,425,426,427,428,429,430,431,432,433,434,435,436,437,438,439,440,441,442,443,444,445,446,447,448,449,450,451,452,453,454,455,456,457,458,459,460,461,462,463,464,465,466,467,468,469,470,471,472,473,474,475,476,477,478,479,480,481,482,483,484,485,486,487,488,489,490,491,492,493,494,495,496,497,498,499,500,501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,545,546,547,548,549,550,551,552,553,554,555,556,557,558,559,560,561,562,563,564,565,566,567,568,569,570,571,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,597,598,599,600,601,602,603,604,605,606,607,608,609,610,611,612,613,614,615,616,617,618,619,620,621,622,623,624,625,626,627,628,629,630,631,632,633,634,635,636,637,638,639,640,641,642,643,644,645,646,647,648,649,650,651,652,653,654,655,656,657,658,659,660,661,662,663,664,665,666,667,668,669,670,671,672,673,674,675,676,677,678,679,680,681,682,683,684,685,686,687,688,689,690,691,692,693,694,695,696,697,698,699,700,701,702,703,704,705,706,707,708,709,710,711,712,713,714,715,716,717,718,719,720,721,722,723,724,725,726,727,728,729,730,731,732,733,734,735,736,737,738,739,740,741,742,743,744,745,746,747,748,749,750,751,752,753,754,755,756,757,758,759,760,761,762,763,764,765,766,767,768,769,770,771,772,773,774,775,776,777,778,779,780,781,782,783,784,785,786,787,788,789,790,791,792,793,794,795,796,797,798,799,800,801,802,803,804,805,806,807,808,809,810,811,812,813,814,815,816,817,818,819,820,821,822,823,824,825,826,827,828,829,830,831,832,833,834,835,836,837,838,839,840,841,842,843,844,845,846,847,848,849,850,851,852,853,854,855,856,857,858,859,860,861,862,863,864,865,866,867,868,869,870,871,872,873,874,875,876,877,878,879,880,881,882,883,884,885,886,887,888,889,890,891,892,893,894,895,896,897,898,899,900,901,902,903,904,905,906,907,908,909,910,911,912,913,914,915,916,917,918,919,920,921,922,923,924,925,926,927,928,929,930,931,932,933,934,935,936,937,938,939,940,941,942,943,944,945,946,947,948,949,950,951,952,953,954,955,956,957,958,959,960,961,962,963,964,965,966,967,968,969,970,971,972,973,974,975,976,977,978,979,980,981,982,983,984,985,986,987,988,989,990,991,992,993,994,995,996,997,998,999,1000,1001,1002,1003,1004,1005,1006,1007,1008,1009,1010,1011,1012,1013,1014,1015,1016,1017,1018,1019,1020,1021,1022,1023,1024,1025,1026,1027,1028,1029,1030,1031,1032,1033,1034,1035,1036,1037,1038,1039,1040,1041,1042,1043,1044,1045,1046,1047,1048,1049,1050,1051,1052,1053,1054,1055,1056,1057,1058,1059,1060,1061,1062,1063,1064,1065,1066,1067,1068,1069,1070,1071,1072,1073,1074,1075,1076,1077,1078,1079,1080,1081,1082,1083,1084,1085,1086,1087,1088,1089,1090,1091,1092,1093,1094,1095,1096,1097,1098,1099,1100,1101,1102,1103,1104,1105,1106,1107,1108,1109,1110,1111,1112,1113,1114,1115,1116,1117,1118,1119,1120,1121,1122,1123,1124,1125,1126,1127,1128,1129,1130,1131,1132,1133,1134,1135,1136,1137,1138,1139,1140,1141,1142,1143,1144,1145,1146,1147,1148,1149,1150,1151,1152,1153,1154,1155,1156,1157,1158,1159,1160,1161,1162,1163,1164,1165,1166,1167,1168,1169,1170,1171,1172,1173,1174,1175,1176,1177,1178,1179,1180,1181,1182,1183,1184,1185,1186,1187,1188,1189,1190,1191,1192,1193,1194,1195,1196,1197,1198,1199,1200,1201,1202,1203,1204,1205,1206,1207,1208,1209,1210,1211,1212,1213,1214,1215,1216,1217,1218,1219,1220,1221,1222,1223,1224,1225,1226,1227,1228,1229,1230,1231,1232,1233,1234,1235,1236,1237,1238,1239,1240,1241,1242,1243,1244,1245,1246,1247,1248,1249,1250,1251,1252,1253,1254,1255,1256,1257,1258,1259,1260,1261,1262,1263,1264) have mixed types. Specify dtype option on import or set low_memory=False.
  credits = pd.read_csv("tmdb_5000_credits.csv")

In [7]:
movie.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [8]:
movie.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4803 non-null   object
 2   homepage              1712 non-null   object
 3   id                    4803 non-null   int64
 4   keywords              4803 non-null   object
 5   original_language     4803 non-null   object
 6   original_title        4803 non-null   object
 7   overview              4800 non-null   object
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   object
 10  production_countries  4803 non-null   object
 11  release_date          4802 non-null   object
 12  revenue               4803 non-null   int64
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   object
 15  status                4803 non-null   object
 16  tagline               3959 non-null   object
 17  title                 4803 non-null   object
 18  vote_average          4803 non-null   float64
 19  vote_count            4803 non-null   int64
dtypes: float64(3), int64(4), object(13)
memory usage: 750.6+ KB

In [9]:
movie.isnull().sum()

budget                     0
genres                     0
homepage                3091
id                         0
keywords                   0
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
dtype: int64

In [10]:
credits.head()

,movie_id,title,cast,crew,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 1255,Unnamed: 1256,Unnamed: 1257,Unnamed: 1258,Unnamed: 1259,Unnamed: 1260,Unnamed: 1261,Unnamed: 1262,Unnamed: 1263,Unnamed: 1264
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
credits.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3863 entries, 0 to 3862
Columns: 1265 entries, movie_id to Unnamed: 1264
dtypes: object(1265)
memory usage: 37.3+ MB

In [12]:
credits.isnull().sum()

movie_id         2365
title            2364
cast             2364
crew             2367
Unnamed: 4       3854
                 ...
Unnamed: 1260    3862
Unnamed: 1261    3862
Unnamed: 1262    3862
Unnamed: 1263    3862
Unnamed: 1264    3862
Length: 1265, dtype: int64

In [13]:
# Merge both datasets on title
movies = movie.merge(credits, on='title')

In [14]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1492 entries, 0 to 1491
Columns: 1284 entries, budget to Unnamed: 1264
dtypes: float64(3), int64(4), object(1277)
memory usage: 14.6+ MB

In [15]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,Unnamed: 1255,Unnamed: 1256,Unnamed: 1257,Unnamed: 1258,Unnamed: 1259,Unnamed: 1260,Unnamed: 1261,Unnamed: 1262,Unnamed: 1263,Unnamed: 1264
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
# Keep important columns
movies = movies[['id', 'title', 'overview', 'keywords', 'genres', 'cast', 'crew']]

# Drop rows with null values
movies.dropna(inplace=True)

In [17]:
movies.head()

,id,title,overview,keywords,genres,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [18]:
# Process 'overview' column
movies['overview'] = movies['overview'].apply(lambda x: x.split())

In [19]:
# Process 'keywords' column
def convert_keywords(obj):
    l = []
    for i in ast.literal_eval(obj):
        l.append(i['name'])
    return l

movies['keywords'] = movies['keywords'].apply(convert_keywords)

In [20]:
# Process 'genres' column
def convert_genres(obj):
    l = []
    for i in ast.literal_eval(obj):
        l.append(i['name'])
    return l

movies['genres'] = movies['genres'].apply(convert_genres)

In [21]:
# Process 'cast' column (top 3 only)
def extract_cast(obj):
    l = []
    count = 0
    for i in ast.literal_eval(obj):
        if count != 3:
            l.append(i['name'])
            count += 1
        else:
            break
    return l

movies['cast'] = movies['cast'].apply(extract_cast)

In [22]:
# Process 'crew' column (get director only)
def extract_director(obj):
    l = []
    try:
        for i in ast.literal_eval(obj):
            if i['job'] == 'Director':
                l.append(i['name'])
                break
    except Exception as e:
        print("Error:", obj[:100])  # print first 100 chars
        return []
    return l

movies['crew'] = movies['crew'].apply(extract_director)

Error: [{"credit_id": "52fe4bf7c3a368484e1a0683", "department": "Production", "gender": 2, "id": 488, "job"
Error: [{"credit_id": "547c22efc3a3685b0000250d", "department": "Sound", "gender": 2, "id": 3687, "job": "S
Error: [{"credit_id": "52fe4256c3a36847f8016875", "department": "Production", "gender": 2, "id": 7, "job":
Error: [{"credit_id": "52fe4a6dc3a36847f81cd53f", "department": "Camera", "gender": 2, "id": 275, "job": "D
Error: [{"credit_id": "54b64442c3a36837ca001428", "department": "Sound", "gender": 2, "id": 3687, "job": "S
Error: [{"credit_id": "578171449251417b950006e0", "department": "Art", "gender": 2, "id": 11423, "job": "Pr

In [23]:

# Tags = Combined features of a movie
# Create 'tags' column by combining overview + keywords + genres + cast + crew
movies['tags'] = movies['overview'] + movies['cast'] + movies['crew'] + movies['keywords'] + movies['genres']
# Remove spaces from tags
movies['tags'] = movies['tags'].apply(lambda x: [i.replace(" ", "") for i in x])

# Stemming : Reduces words to their base form. Example: Loved, Loving, Loves -> Love
ps = PorterStemmer()

def stemming(text):
    l = []
    for i in text:
        l.append(ps.stem(i))
    return " ".join(l)

movies['tags'] = movies['tags'].apply(stemming)


movies['tags'].head()

0    in the 22nd century, a parapleg marin is dispa...
1    captain barbossa, long believ to be dead, ha c...
2    a cryptic messag from bond’ past send him on a...
3    follow the death of district attorney harvey d...
4    john carter is a war-weary, former militari ca...
Name: tags, dtype: object

In [24]:
# Final dataset with relevant columns
movies = movies[['id', 'title', 'tags']]
movies.head()

,id,title,tags
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believ to be dead, ha c..."
2,206647,Spectre,a cryptic messag from bond’ past send him on a...
3,49026,The Dark Knight Rises,follow the death of district attorney harvey d...
4,49529,John Carter,"john carter is a war-weary, former militari ca..."

In [25]:
# Vectorization: Convert text data into numerical data using CountVectorizer
vectorizer = CountVectorizer(max_features=500, stop_words='english')
vectors = vectorizer.fit_transform(movies['tags']).toarray()

# Cosine similarity: Measure similarity between two vectors. Range: 0 to 1. Closer to 1 means more similar.
similarity = cosine_similarity(vectors)

In [26]:
# Recommendation function:
'''
def Recommendation_system(movie_title):
    movie_index = movies[movies['title'] == movie_title].index[0] # Get index of the movie
    distances = sorted(list(enumerate(similarity[movie_index])), reverse=True, key=lambda x: x[1]) # Sort movies based on similarity score

    for i in distances[1:20]: # Loop through the top 20 similar movies (excluding the given movie itself)
        print(movies.iloc[i[0]].title) # Print the titles of the top 20 similar movies (excluding the given movie itself)
'''

def recommend(movie_title):
    movie_index = movies[movies['title'] == movie_title].index[0] # Get index of the movie
    distances = similarity[movie_index] # Get similarity scores for all movies with the given movie

    movies_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x: x[1])[1:6] # Get top 5 similar movies (excluding the given movie itself)

    recommended = [] # Initialize an empty list to store recommended movie titles
    for i in movies_list: # Loop through the list of similar movies
        recommended.append(movies.iloc[i[0]].title) # Append the title of the recommended movie to the list

    return recommended

# Example usage
# Recommendation_system('Avatar')

In [27]:
# Save the model and data
pickle.dump(movies, open('model.pkl', 'wb')) # Save the movies dataframe as a pickle file
pickle.dump(similarity, open('similarity.pkl', 'wb')) # Save the similarity matrix as a pickle file

Testing the MODEL

In [28]:
recommend("Avatar")

['Independence Day',
 'Aliens vs Predator: Requiem',
 'Beowulf',
 'Small Soldiers',
 'Jupiter Ascending']

# Implement User-Based Collaborative Filtering

In [ ]:
#!pip install scikit-surprise

In [ ]:
#!pip install numpy==1.24.4

In [ ]:
from surprise import Dataset, Reader
from surprise.model_selection import train_test_split
from surprise import KNNBasic
from surprise import accuracy

Due to lack of real user interaction data in the TMDB dataset, synthetic users were generated and movie vote averages were used as proxy ratings to enable collaborative filtering.

In [ ]:
# Create Ratings Dataset

movie1 = pd.read_csv('tmdb_5000_movies.csv')

# Use original movie dataframe (before dropping columns if possible)
ratings_df = movie1[['id', 'vote_average']].copy()

# Rename columns
ratings_df.columns = ['movieId', 'rating']

# Create synthetic users
num_users = 1000
ratings_df['userId'] = np.random.randint(1, num_users+1, size=len(ratings_df))

ratings_df = ratings_df[['userId', 'movieId', 'rating']]

ratings_df.head()

   userId  movieId  rating
0     698    19995     7.2
1     648      285     6.9
2     980   206647     6.3
3     670    49026     7.6
4     706    49529     6.1

In [ ]:
# Load Data into Surprise

reader = Reader(rating_scale=(0, 10))

data = Dataset.load_from_df(
    ratings_df[['userId', 'movieId', 'rating']],
    reader
)

trainset, testset = train_test_split(data, test_size=0.2)

In [ ]:
# Train User-Based Collaborative Model

model = KNNBasic(sim_options={
    'name': 'cosine',
    'user_based': True
})

model.fit(trainset)

Computing the cosine similarity matrix...
Done computing similarity matrix.

In [ ]:
pickle.dump(model, open('collab_model.pkl', 'wb'))
pickle.dump(ratings_df, open('ratings_df.pkl', 'wb'))

In [ ]:
# Evaluate Model

predictions = model.test(testset)
accuracy.rmse(predictions)

RMSE: 1.0789

1.0789373302732899

The model achieved an RMSE of 1.16, indicating moderate prediction error, which is expected due to synthetic user generation and absence of real interaction data

In [ ]:
# Recommendation Function (Collaborative)

def recommend_collaborative(user_id, top_n=5):

    movie_ids = ratings_df['movieId'].unique()
    predictions = []

    for movie_id in movie_ids:
        pred = model.predict(user_id, movie_id)
        predictions.append((movie_id, pred.est))

    # Sort by predicted rating
    predictions.sort(key=lambda x: x[1], reverse=True)

    top_movies = predictions[:top_n]

    # Convert to titles
    recommended = []
    for movie_id, score in top_movies:
        title = movies[movies['id'] == movie_id]['title'].values
        if len(title) > 0:
            recommended.append((title[0], score))

    return recommended

In [ ]:
# Test Collaborative Filtering

recommend_collaborative(user_id=1)

[('Avatar', 6.078344612181156),
 ("Pirates of the Caribbean: At World's End", 6.078344612181156)]

# Hybrid Methods

In [ ]:
def recommend_with_scores(movie_title, top_n=10):
    movie_index = movies[movies['title'] == movie_title].index[0]
    distances = similarity[movie_index]

    movies_list = sorted(
        list(enumerate(distances)),
        reverse=True,
        key=lambda x: x[1]
    )[1:top_n+1]

    results = []

    for i in movies_list:
        results.append({
            "movie_id": movies.iloc[i[0]].id,
            "title": movies.iloc[i[0]].title,
            "content_score": float(i[1])
        })

    return results

In [ ]:
# Hybrid Function (MAIN PART). we combine both models

def hybrid_recommend(user_id, movie_title, alpha=0.5, top_n=5):

    # Step 1: Get content-based recommendations
    content_results = recommend_with_scores(movie_title, top_n=20)

    hybrid_results = []

    for item in content_results:
        movie_id = item['movie_id']
        content_score = item['content_score']

        # Step 2: Collaborative score
        collab_score = model.predict(user_id, movie_id).est

        # Step 3: Normalize collaborative score (important!)
        collab_score_norm = collab_score / 10  # since ratings are 0–10

        # Step 4: Combine scores
        final_score = (alpha * content_score) + ((1 - alpha) * collab_score_norm)

        hybrid_results.append({
            "title": item['title'],
            "final_score": final_score
        })

    # Step 5: Sort results
    hybrid_results = sorted(
        hybrid_results,
        key=lambda x: x['final_score'],
        reverse=True
    )

    return hybrid_results[:top_n]

In [ ]:
# Test Hybrid System

hybrid_recommend(user_id=1, movie_title="Avatar")

[{'title': 'Independence Day', 'final_score': 0.5909361545500217},
 {'title': 'Aliens vs Predator: Requiem', 'final_score': 0.5338444829159199},
 {'title': 'Beowulf', 'final_score': 0.5333329644796195},
 {'title': 'Small Soldiers', 'final_score': 0.5266168976505801},
 {'title': 'Jupiter Ascending', 'final_score': 0.5112393378247401}]

Your hybrid system is working correctly because:
- It is producing ranked recommendations
- Scores are not identical → good sign (variation exists)
- Movies are relevant to Avatar (sci-fi / action genre overlap)
- Output is stable and sorted properly

The hybrid recommender successfully combines content-based similarity with user-based collaborative filtering using a weighted average approach. Results demonstrate strong thematic relevance, with slight ranking adjustments introduced by collaborative predictions. Due to synthetic user generation, collaborative influence is limited, resulting in a system that is primarily content-driven with collaborative refinement.

A hybrid recommendation system was implemented by combining content-based similarity scores with collaborative filtering predictions. A weighted average approach was used where both models contributed equally (α = 0.5). This ensures recommendations are influenced by both item similarity and user preference patterns, improving robustness and reducing limitations of individual approaches.

In [ ]:
'''
from flask import Flask, request, render_template, jsonify
import requests
import pandas as pd
import pickle
import numpy as np
import threading

from surprise import KNNBasic

app = Flask(__name__)

# =========================
# LOAD MODELS
# =========================
movies = pickle.load(open('model.pkl', 'rb'))
similarity = pickle.load(open('similarity.pkl', 'rb'))

model = pickle.load(open('collab_model.pkl', 'rb'))
ratings_df = pickle.load(open('ratings_df.pkl', 'rb'))

# =========================
# POSTER FUNCTION
# =========================
def fetch_poster(movie_id):
    url = f"https://api.themoviedb.org/3/movie/{movie_id}?api_key=390e76286265f7638bb6b19d86474639&language=en-US"
    data = requests.get(url).json()

    poster_path = data.get('poster_path')
    if not poster_path:
        return None

    return "https://image.tmdb.org/t/p/w500/" + poster_path

# =========================
# CONTENT-BASED
# =========================
def recommend_content(movie_title, top_n=5):

    idx_list = movies[movies['title'] == movie_title].index
    if len(idx_list) == 0:
        return []

    idx = idx_list[0]
    distances = similarity[idx]

    results = sorted(
        list(enumerate(distances)),
        reverse=True,
        key=lambda x: x[1]
    )[1:top_n+1]

    output = []
    for i in results:
        output.append({
            "movie_id": int(movies.iloc[i[0]].id),
            "title": movies.iloc[i[0]].title,
            "score": float(i[1])
        })

    return output

# =========================
# COLLABORATIVE FILTERING
# =========================
def recommend_collab(user_id, top_n=5):

    movie_ids = ratings_df['movieId'].unique()

    preds = []
    for mid in movie_ids:
        pred = model.predict(user_id, mid)
        preds.append((mid, pred.est))

    preds.sort(key=lambda x: x[1], reverse=True)

    results = []
    for mid, score in preds[:top_n]:
        match = movies[movies['id'] == mid]['title']
        if not match.empty:
            results.append({
                "title": match.values[0],
                "score": float(score)
            })

    return results

# =========================
# HYBRID MODEL
# =========================
def hybrid_recommend(user_id, movie_title, alpha=0.5, top_n=5):

    content_results = recommend_content(movie_title, top_n=20)

    hybrid = []

    for item in content_results:
        movie_id = item['movie_id']

        pred = model.predict(user_id, movie_id).est
        collab_norm = pred / 10  # normalize to 0–1

        final_score = alpha * item['score'] + (1 - alpha) * collab_norm

        hybrid.append({
            "title": item['title'],
            "score": final_score
        })

    hybrid = sorted(hybrid, key=lambda x: x['score'], reverse=True)

    return hybrid[:top_n]

# =========================
# UI ROUTES
# =========================
@app.route('/')
def home():
    movie_list = movies['title'].tolist()
    return render_template('index.html', movie_list=movie_list)

@app.route('/recommend', methods=['POST'])
def recommend():
    movie_title = request.form['selected_movie']

    titles = [x['title'] for x in recommend_content(movie_title, 10)]

    return render_template(
        'index.html',
        movie_list=movies['title'].tolist(),
        recommended_movie_titles=titles
    )

# =========================
# API ROUTES
# =========================
@app.route('/api/content')
def api_content():
    movie = request.args.get('movie')
    return jsonify(recommend_content(movie))

@app.route('/api/collab')
def api_collab():
    user_id = int(request.args.get('user_id'))
    return jsonify(recommend_collab(user_id))

@app.route('/api/hybrid')
def api_hybrid():
    user_id = int(request.args.get('user_id'))
    movie = request.args.get('movie')
    return jsonify(hybrid_recommend(user_id, movie))

# =========================
# RUN FLASK (COLAB SAFE)
# =========================
if __name__ == '__main__':
    threading.Thread(
        target=lambda: app.run(port=5000, use_reloader=False)
    ).start()

'''

 * Serving Flask app '__main__'
 * Debug mode: off

In [ ]:
'''
import time
import threading

def run_app():
    app.run(port=5000, use_reloader=False, debug=False)

thread = threading.Thread(target=run_app)
thread.start()

time.sleep(5)

'''

 * Serving Flask app '__main__'
 * Debug mode: off

Address already in use
Port 5000 is in use by another program. Either identify and stop that program, or start the server with a different port.

In [ ]:
'''
import requests

response = requests.get("http://127.0.0.1:5000/api/content?movie=Avatar")
print(response.json())

'''

INFO:werkzeug:127.0.0.1 - - [15/Apr/2026 21:26:27] "GET /api/content?movie=Avatar HTTP/1.1" 200 -

[{'movie_id': 602, 'score': 0.5740378478819278, 'title': 'Independence Day'}, {'movie_id': 440, 'score': 0.45985450461372435, 'title': 'Aliens vs Predator: Requiem'}, {'movie_id': 2310, 'score': 0.4588314677411235, 'title': 'Beowulf'}, {'movie_id': 11551, 'score': 0.44539933408304444, 'title': 'Small Soldiers'}, {'movie_id': 76757, 'score': 0.41464421443136457, 'title': 'Jupiter Ascending'}]

In [ ]:
'''
import requests

response = requests.get("http://127.0.0.1:5000/api/collab?user_id=1")
print(response.json())
'''

INFO:werkzeug:127.0.0.1 - - [15/Apr/2026 21:31:48] "GET /api/collab?user_id=1 HTTP/1.1" 200 -

[{'score': 6.078344612181156, 'title': 'Avatar'}, {'score': 6.078344612181156, 'title': "Pirates of the Caribbean: At World's End"}]

In [ ]:
'''
import requests

res = requests.get("http://127.0.0.1:5000/api/hybrid?user_id=1&movie=Avatar")
print(res.json())
'''

INFO:werkzeug:127.0.0.1 - - [15/Apr/2026 21:31:48] "GET /api/hybrid?user_id=1&movie=Avatar HTTP/1.1" 200 -

[{'score': 0.5909361545500217, 'title': 'Independence Day'}, {'score': 0.5338444829159199, 'title': 'Aliens vs Predator: Requiem'}, {'score': 0.5333329644796195, 'title': 'Beowulf'}, {'score': 0.5266168976505801, 'title': 'Small Soldiers'}, {'score': 0.5112393378247401, 'title': 'Jupiter Ascending'}]